name: Flask CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Validate MongoDB secret
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: |
          if [[ "$MONGO_URI" == mongodb+srv://* || "$MONGO_URI" == mongodb://* ]]; then
            echo "MongoDB URI format is correct."
          else
            echo "ERROR: MONGO_URI does not start with mongodb:// or mongodb+srv://"
            exit 1
          fi

      - name: Run tests
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          SECRET_KEY: ${{ secrets.SECRET_KEY_FLASK }}
        run: |
          pytest -v